spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aita_meetup
    username: aita_meetup
    password: aita_meetup
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5

springdoc:
  swagger-ui:
    path: /

aita-meetup:
  batch-size: 500
  random-guest:
    queue-size: 100
    reload-interval: 10
    reload-threshold: 20

images:
  boarding-pass:
    width: 1280
    height: 464
    template: /boarding/template.png
    barcode-drawing-suites:
      - name: mainBarcode
        x: 500
        y: 10
      - name: ticketBarcode
        x: 945
        y: 315
    text-drawing-suites:
      - name: mainName
        x: 47
        y: 225
        color:
          r: 0
          g: 0
          b: 0
        font:
          name: TimesRoman
          font-size: 37
          style: 1
        wrap-length: 20
      - name: mainDestination
        x: 47
        y: 340
        color:
          r: 0
          g: 0
          b: 0
        font:
          name: TimesRoman
          font-size: 25
          style: 1
        wrap-length: 18
      - name: mainDate
        x: 400
        y: 340
        color:
          r: 0
          g: 0
          b: 0
        font:
          name: TimesRoman
          font-size: 25
          style: 1
      - name: mainTime
        x: 600
        y: 340
        color:
          r: 0
          g: 0
          b: 0
        font:
          name: TimesRoman
          font-size: 25
          style: 1
      - name: ticketName
        x: 975
        y: 100
        color:
          r: 255
          g: 255
          b: 255
        font:
          name: TimesRoman
          font-size: 23
          style: 1
        wrap-length: 20
      - name: ticketDestination
        x: 975
        y: 190
        color:
          r: 255
          g: 255
          b: 255
        font:
          name: TimesRoman
          font-size: 23
          style: 1
        wrap-length: 18
      - name: ticketDate
        x: 975
        y: 315
        color:
          r: 255
          g: 255
          b: 255
        font:
          name: TimesRoman
          font-size: 23
          style: 1
      - name: ticketTime
        x: 1155
        y: 315
        color:
          r: 255
          g: 255
          b: 255
        font:
          name: TimesRoman
          font-size: 23
          style: 1
  barcode:
    width: 280
    height: 100

---
spring:
  profiles: debug-log

logging:
  level:
    me.likeanowl.aitameetup: debug
